apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | quote }}
  NEXT_PUBLIC_OPENAI_DOMAIN_KEY: {{ .Values.secrets.nextPublicOpenaiDomainKey | quote }}